// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHwZ9pgr-mHxZTQUTjaqdOt8uEMi_aVk4',
    appId: '1:609537756613:web:6033c7cb66509502044fac',
    messagingSenderId: '609537756613',
    projectId: 'shopease-41e09',
    authDomain: 'shopease-41e09.firebaseapp.com',
    storageBucket: 'shopease-41e09.firebasestorage.app',
    measurementId: 'G-3D0MBWQ186',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAINSu4bs-8THeP3Iwq24rRla0WhjOsIds',
    appId: '1:609537756613:android:dceac8289857ded3044fac',
    messagingSenderId: '609537756613',
    projectId: 'shopease-41e09',
    storageBucket: 'shopease-41e09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqO1Sx5UCouU3VrCl7JAeUtdUPKXgNzMk',
    appId: '1:609537756613:ios:6fd0e67a6323a816044fac',
    messagingSenderId: '609537756613',
    projectId: 'shopease-41e09',
    storageBucket: 'shopease-41e09.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );
}
